"use client";
import { BookOpenText, PhoneCall, Search, UsersRound, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { apiRequest } from "@/lib/api";
import type { SearchResults } from "@/lib/types";

export function GlobalSearch({ businessId }:{ businessId:string }) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResults|null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { const shortcut=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();inputRef.current?.focus()}}; window.addEventListener("keydown",shortcut); return()=>window.removeEventListener("keydown",shortcut)},[]);
  useEffect(() => { if(query.trim().length<2){queueMicrotask(()=>setResults(null));return} const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);apiRequest<SearchResults>(`/backend/api/v1/businesses/${businessId}/search/?q=${encodeURIComponent(query.trim())}`,{signal:controller.signal}).then(setResults).catch(reason=>{if(reason.name!=="AbortError")setResults(null)}).finally(()=>setLoading(false))},220);return()=>{window.clearTimeout(timer);controller.abort()}},[businessId,query]);
  const count=results?results.calls.length+results.leads.length+results.services.length+results.faqs.length:0;
  function close(){setQuery("");setResults(null);inputRef.current?.blur()}
  return <div className="global-search"><div className="search-box"><Search size={17}/><input ref={inputRef} value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Escape")close()}} placeholder="Search calls, leads, services…" aria-label="Search workspace"/><kbd>⌘ K</kbd>{query&&<button onClick={close} aria-label="Clear search"><X size={14}/></button>}</div>{query.trim().length>=2&&<div className="search-results" role="dialog" aria-label="Search results"><div className="search-results-head"><strong>{loading?"Searching…":`${count} result${count===1?"":"s"}`}</strong><span>for “{query.trim()}”</span></div>{!loading&&results&&count===0&&<p className="search-empty">No matching calls, leads, services, or answers.</p>}{results?.calls.map(item=><Link href="/dashboard/calls" onClick={close} key={`call-${item.id}`}><PhoneCall size={16}/><span><strong>{item.caller_name||item.caller_phone||"Unknown caller"}</strong><small>{item.lead_requirement||"Call conversation"}</small></span><em>Call</em></Link>)}{results?.leads.map(item=><Link href="/dashboard/leads" onClick={close} key={`lead-${item.id}`}><UsersRound size={16}/><span><strong>{item.caller_name||item.caller_phone||"Unknown caller"}</strong><small>{item.requirement||"Captured lead"}</small></span><em>Lead</em></Link>)}{results?.services.map(item=><Link href="/dashboard/knowledge" onClick={close} key={`service-${item.id}`}><BookOpenText size={16}/><span><strong>{item.name}</strong><small>{item.description}</small></span><em>Service</em></Link>)}{results?.faqs.map(item=><Link href="/dashboard/knowledge" onClick={close} key={`faq-${item.id}`}><BookOpenText size={16}/><span><strong>{item.question}</strong><small>{item.answer}</small></span><em>Answer</em></Link>)}</div>}{query.trim().length>=2&&<button className="search-scrim" aria-label="Close search" onClick={close}/>}</div>;
}
